######################################################################
# Automatically generated by qmake (2.01a) lun ago 24 23:40:37 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += window.h
SOURCES += main.cc window.cc
