######################################################################
# Automatically generated by qmake (2.01a) dom ago 23 10:17:06 2009
######################################################################

TEMPLATE = subdirs

# Directories
SUBDIRS += button buttons hello lineedit quitbutton vplayer
