######################################################################
# Automatically generated by qmake (2.01a) ven ago 21 23:08:47 2009
######################################################################

TEMPLATE = subdirs

# Directories
SUBDIRS += button
