######################################################################
# Automatically generated by qmake (2.01a) sab ago 22 00:16:20 2009
######################################################################

TEMPLATE = subdirs

# Directories
SUBDIRS += button
