######################################################################
# Automatically generated by qmake (2.01a) mer ago 26 01:11:36 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += window.h
SOURCES += main.cc window.cc
