######################################################################
# Automatically generated by qmake (2.01a) sab ago 22 00:23:12 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += clickhandler.h window.h
SOURCES += clickhandler.cc main.cc window.cc
