######################################################################
# Automatically generated by qmake (2.01a) ven ago 21 22:57:31 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += clickhandler.h
SOURCES += clickhandler.cc main.cc
