######################################################################
# Automatically generated by qmake (2.01a) gio ago 27 21:54:58 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += phonon

# Input
HEADERS += window.h
SOURCES += main.cc window.cc
