######################################################################
# Automatically generated by qmake (2.01a) dom ago 23 10:06:47 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += window.h
SOURCES += main.cc window.cc
